### ISSUE TITLE
Add huahua node PROBLEM

### ISSUE THREAD

**Issue by lgattoni** [ChihuahuaChain/chihuahua#119]
Hello,
(thanks for your help)
I have debian 11.9 and I followed your procedure but I have errors when starting the daemon and I have a few remarks:
- First: we need go 1.21 or in your file Makefile, GO_VERSION = "1.20" (I changed to make install binary chihuahuad) 
- My chihuahuad version is v7 and my cosmovisor version is V1.3.0.
- I tested with chihuahuad version 6 and different version of cosmovisor, i have the same error...
- My error mess:

Jun 03 11:26:56 Maat-cosmos cosmovisor[117414]: 11:26AM INF initializing blockchain state from genesis.json module=server
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: panic: minimum commission rate cannot be nil: <nil>
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: goroutine 6 [running]:
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.InitGenesis({{0x3819eb0, 0xc00099c400}, {0x384f790, 0xc000b20e00}, {0x383c2a0, 0xc0009de640}, {0x384beb8, 0xc001212b60}, {0x384ef98, 0xc000dc4de0}, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/x/staking/keeper/genesis.go:31 +0x1b16
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{_, _}}, _, {_, _}, {_, _}, {_, _}}, {{0x383a6e0, ...}, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/x/staking/module.go:172 +0x125
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x383a6e0, 0x4f1b0e0}, {0x38501e0, 0xc00238b340}, {{0x0, 0x0}, {0xc000c5c0e0, 0xb}, 0x0, ...}, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/types/module/module.go:357 +0x373
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/ChihuahuaChain/chihuahua/app.(*App).InitChainer(_, {{0x383a6e0, 0x4f1b0e0}, {0x38501e0, 0xc00238b340}, {{0x0, 0x0}, {0xc000c5c0e0, 0xb}, 0x0, ...}, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/ChihuahuaChain/chihuahua/app/app.go:957 +0x18f
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00077ef00, {{0x0, 0xed94a8194, 0x0}, {0xc000c5c0e0, 0xb}, 0xc00239e280, {0x4f1b0e0, 0x0, 0x0}, ...})
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/baseapp/abci.go:78 +0x515
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0xc001307f20, {{0x0, 0xed94a8194, 0x0}, {0xc000c5c0e0, 0xb}, 0xc00239e280, {0x4f1b0e0, 0x0, 0x0}, ...})
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/abci/client/local_client.go:275 +0x102
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0xc000013710, {{0x0, 0xed94a8194, 0x0}, {0xc000c5c0e0, 0xb}, 0xc00239e280, {0x4f1b0e0, 0x0, 0x0}, ...})
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/proxy/app_conn.go:85 +0x198
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0x2868bdb, 0x6}}, {0xc000c5c0e0, 0xb}, 0x1, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/consensus/replay.go:336 +0xef8
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc00170e080, {0x383ae50, 0x4f1b0e0}, {0x38528b0?, 0xc000107420?})
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/consensus/replay.go:274 +0x3b8
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0x2868bdb, 0x6}}, {0xc000c5c0e0, 0xb}, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/node/node.go:449 +0x1a8
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/node.NewNodeWithContext({0x383ae50, 0x4f1b0e0}, 0xc00003fce0, {0x381f050, 0xc00027ca00}, 0xc00237e8b0, {0x380f3a0, 0xc002394d50}, 0x1?, 0x32e79c8, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/node/node.go:929 +0x55b
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cometbft/cometbft/node.NewNode(0x0?, {0x381f050?, 0xc00027ca00?}, 0x0?, {0x380f3a0?, 0xc002394d50?}, 0x1?, 0x4f1b0e0?, 0x0?, {0x383a788, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cometbft/cometbft@v0.37.4/node/node.go:849 +0xa9
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3851040, 0xc00134a600}, 0x0, {0x0, 0x0}, {0x385bca0, ...}, ...}, ...)
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/server/start.go:372 +0x6f7
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/server/start.go:153 +0x45
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/server/start.go:617 +0x22
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]: created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile in goroutine 1
Jun 03 11:27:02 Maat-cosmos cosmovisor[117414]:         github.com/cosmos/cosmos-sdk@v0.47.8/server/start.go:616 +0x22f
Jun 03 11:27:02 Maat-cosmos cosmovisor[117408]: Error: exit status 2

**Comment by lgattoni** [comment]
Ok:
- My node is ok now But to install node from scratch: before start chihuahuad service: Download latest polkachu snapshot : update data directory and start: wait index finish and follow the rest of installation
