### ISSUE TITLE
Upgrade issue: panic: cannot delete latest saved version

### ISSUE THREAD

**Issue by chleeab** [ChihuahuaChain/chihuahua#20]
#### Description
When the node upgraded from v1.1.1 to v2.0.0-rc-2 in testnet, it stopped with this error: `panic: cannot delete latest saved version`

At first, I use cosmosvisor with this setting
```Configurable Values:
  DAEMON_HOME: /home/chihuahua/.chihuahua
  DAEMON_NAME: chihuahuad
  DAEMON_ALLOW_DOWNLOAD_BINARIES: false
  DAEMON_RESTART_AFTER_UPGRADE: true
  DAEMON_POLL_INTERVAL: 300ms
  UNSAFE_SKIP_BACKUP: false
  DAEMON_PREUPGRADE_MAX_RETRIES: 0
Derived Values:
        Root Dir: /home/chihuahua/.chihuahua/cosmovisor
     Upgrade Dir: /home/chihuahua/.chihuahua/cosmovisor/upgrades
     Genesis Bin: /home/chihuahua/.chihuahua/cosmovisor/genesis/bin/chihuahuad
  Monitored File: /home/chihuahua/.chihuahua/data/upgrade-info.json
```
` /home/chihuahua/.chihuahua/cosmovisor/genesis/bin/chihuahuad version` is `v1.1.1`
`/home/chihuahua/.chihuahua/cosmovisor/upgrades/chiwawasm/bin/chihuahuad version` is `v2.0.0-rc-2`

Then, I stop comosvisor service and upgrade manually. Same error returned.

I deleted the `data` directory and resync from height 1 manually. The node stopped at upgrade height as expected. After manual upgrade to `v2.0.0-rc-2`, `chihuahua start` again. Same error.

#### Error Log
```
1:12PM INF starting ABCI with Tendermint
1:12PM INF Starting multiAppConn service impl=multiAppConn module=proxy
1:12PM INF Starting localClient service connection=query impl=localClient module=abci-client
1:12PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
1:12PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
1:12PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
1:12PM INF Starting EventBus service impl=EventBus module=events
1:12PM INF Starting PubSub service impl=PubSub module=pubsub
1:12PM INF Starting IndexerService service impl=IndexerService module=txindex
1:12PM INF ABCI Handshake App Info hash="\x10��K�\b��>��q73�����9-�L��pM\x10�Pdm" height=39999 module=consensus protocol-version=0 software-version=v2.0.0-rc-2
1:12PM INF ABCI Replay Blocks appHeight=39999 module=consensus stateHeight=39999 storeHeight=40000
1:12PM INF Replay last block using real app module=consensus
1:12PM INF applying upgrade "chiwawasm" at height: 40000
1:12PM INF adding a new module: authz
1:12PM INF adding a new module: wasm
1:12PM INF minted coins from module account amount=20744932813737344787stake from=mint module=x/bank
1:12PM INF executed block height=40000 module=consensus num_invalid_txs=0 num_valid_txs=0
panic: cannot delete latest saved version (11)

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc0000ea420)
        github.com/cosmos/cosmos-sdk@v0.45.1/store/rootmulti/store.go:450 +0x1b6
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0000ea420)
        github.com/cosmos/cosmos-sdk@v0.45.1/store/rootmulti/store.go:424 +0x175
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00123c1a0)
        github.com/cosmos/cosmos-sdk@v0.45.1/baseapp/abci.go:308 +0x231
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000b8af60)
        github.com/tendermint/tendermint@v0.34.16/abci/client/local_client.go:264 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x341a358)
        github.com/tendermint/tendermint@v0.34.16/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc000c92c78, 0x8}}, {0xc000056630, 0x15}, 0x1, 0x9c40, {{0xc001023980, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.16/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000c92c78, 0x8}}, {0xc000056630, 0x15}, 0x1, 0x9c40, {{0xc001023980, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.16/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc000c92c78, 0x8}}, {0xc000056630, 0x15}, 0x1, 0x9c3f, {{0xc0010221e0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.16/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc000c92c78, 0x8}}, {0xc000056630, 0x15}, 0x1, 0x9c3f, {{0xc0010221e0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.16/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000ccdf90, {0x254ad40, 0xc0000b32b0})
        github.com/tendermint/tendermint@v0.34.16/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc000c92c78, 0x8}}, {0xc000056630, 0x15}, 0x1, 0x9c3f, ...}, ...)
        github.com/tendermint/tendermint@v0.34.16/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001159040, {0x24fa0b0, 0xc000e6f7c0}, 0xc0014272d0, {0x24dba00, 0xc000f71260}, 0x0, 0x0, 0xc001427450, {0x251df00, ...}, ...)
        github.com/tendermint/tendermint@v0.34.16/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x255beb8, 0xc00126c7e0}, {0xc000ffbf40, 0x15}, {0x25265e0, 0xc000f7f990}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:263 +0x765
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00118b900, {0x341a358, 0x0, 0x0})
        github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc00118b900, {0x341a358, 0x0, 0x0})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000beca00)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x22d6100, {0xc000ffa0c0, 0x1a})
        github.com/cosmos/cosmos-sdk@v0.45.1/server/cmd/execute.go:36 +0x1eb
main.main()
        github.com/ChihuahuaChain/chihuahua/cmd/chihuahuad/main.go:21 +0x78
```

Cofferoaster from CafeValidator provided a snapshot with data slightly after the upgrade height, the node cashed with same error after syncing for a few blocks.

#### Error Log
```
2:02PM INF committed state app_hash=3E4F88035215059B5C36277B18BF94AE39769C4A7B40C399BD86A6C6850D3F5A height=41879 module=state num_txs=0
2:02PM INF indexed block height=41879 module=txindex
2:02PM INF minted coins from module account amount=20751881919254325803stake from=mint module=x/bank
2:02PM INF executed block height=41880 module=state num_invalid_txs=0 num_valid_txs=0
panic: cannot delete latest saved version (1881)
```

#### Pruning Setting in app.toml

```
pruning = "custom"

# These are applied if and only if the pruning strategy is custom.
pruning-keep-recent = "100"
pruning-keep-every = "0"
pruning-interval = "10"
```

#### How to Solve the Error

Change the pruning setting to `pruning="default"`. Resync again with the snapshot at around height 41000. The node start syncing without error.

**Comment by PolkachuIntern** [comment]
Same setting, same error, and the same solution to get the chain going again. After the chain passes the upgrade height, reverting back to the custom pruning causes no additional issues.

**Comment by kleimanb81** [comment]
Polk, you truly are a hidden legend :)

**Comment by lydia-pierce** [comment]
Seemed to be an issue with the cosmos-sdk, since we have upgraded, it is no longer an issue.
